management.endpoints.web.exposure.include: hawtio,jolokia
hawtio.authenticationEnabled: false

activemq:
  broker.url: "tcp://0.0.0.0:61616"
  queue.name: "names"

spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
      path: "/h2"
      settings.trace: false
      settings.web-allow-others: false
